export const SITE_NAME = "SpotU";
export const SITE_TAGLINE = "Tu spot publicitario ideal";
export const SITE_DESCRIPTION =
  "Marketplace de publicidad que conecta anunciantes, espacios publicitarios y agencias de marketing.";

export const NAV_LINKS = [
  { label: "Explorar", href: "/feed" },
  { label: "Publicar", href: "/publish" },
] as const;

export const USER_ROLES = {
  advertiser: {
    label: "Quiero anunciarme",
    description: "Busca espacios publicitarios y agencias para tu marca",
    icon: "Megaphone",
  },
  space_owner: {
    label: "Tengo un espacio publicitario",
    description: "Publica tu espacio y conecta con anunciantes",
    icon: "MapPin",
  },
  agency: {
    label: "Soy agencia de marketing",
    description: "Ofrece tus servicios a anunciantes y gestiona espacios",
    icon: "Briefcase",
  },
} as const;

export const SPACE_CATEGORIES = [
  { value: "billboard", label: "Valla publicitaria" },
  { value: "led_screen", label: "Pantalla LED" },
  { value: "sports_venue", label: "Recinto deportivo" },
  { value: "social_media", label: "Red social" },
  { value: "website", label: "Sitio web" },
  { value: "app", label: "App móvil" },
  { value: "print", label: "Impreso" },
  { value: "radio", label: "Radio" },
  { value: "podcast", label: "Podcast" },
  { value: "other", label: "Otro" },
] as const;

export const AGENCY_SERVICES = [
  { value: "campaign_management", label: "Gestión de campañas" },
  { value: "creative_design", label: "Diseño creativo" },
  { value: "media_buying", label: "Media buying" },
  { value: "social_media_management", label: "Manejo de redes" },
  { value: "seo_sem", label: "SEO/SEM" },
  { value: "branding", label: "Branding" },
] as const;

export const PRICE_PERIODS = [
  { value: "day", label: "Por día" },
  { value: "week", label: "Por semana" },
  { value: "month", label: "Por mes" },
  { value: "campaign", label: "Por campaña" },
] as const;

// Primary markets (shown in profile/publish for quick selection)
export const MARKETS = [
  { value: "CO", label: "Colombia" },
  { value: "MX", label: "México" },
  { value: "US", label: "Estados Unidos" },
] as const;

// Full country list for publish forms (ISO 3166-1 alpha-2)
export const ALL_COUNTRIES = [
  { value: "AF", label: "Afganistán" },
  { value: "AL", label: "Albania" },
  { value: "DE", label: "Alemania" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "SA", label: "Arabia Saudita" },
  { value: "DZ", label: "Argelia" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaiyán" },
  { value: "BS", label: "Bahamas" },
  { value: "BD", label: "Bangladés" },
  { value: "BE", label: "Bélgica" },
  { value: "BZ", label: "Belice" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia y Herzegovina" },
  { value: "BR", label: "Brasil" },
  { value: "BN", label: "Brunéi" },
  { value: "BG", label: "Bulgaria" },
  { value: "CA", label: "Canadá" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CY", label: "Chipre" },
  { value: "CO", label: "Colombia" },
  { value: "KR", label: "Corea del Sur" },
  { value: "CR", label: "Costa Rica" },
  { value: "HR", label: "Croacia" },
  { value: "CU", label: "Cuba" },
  { value: "DK", label: "Dinamarca" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egipto" },
  { value: "SV", label: "El Salvador" },
  { value: "AE", label: "Emiratos Árabes Unidos" },
  { value: "SK", label: "Eslovaquia" },
  { value: "SI", label: "Eslovenia" },
  { value: "ES", label: "España" },
  { value: "US", label: "Estados Unidos" },
  { value: "ET", label: "Etiopía" },
  { value: "PH", label: "Filipinas" },
  { value: "FI", label: "Finlandia" },
  { value: "FR", label: "Francia" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Grecia" },
  { value: "GT", label: "Guatemala" },
  { value: "HT", label: "Haití" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hong Kong" },
  { value: "HU", label: "Hungría" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IQ", label: "Irak" },
  { value: "IR", label: "Irán" },
  { value: "IE", label: "Irlanda" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italia" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japón" },
  { value: "JO", label: "Jordania" },
  { value: "KZ", label: "Kazajistán" },
  { value: "KE", label: "Kenia" },
  { value: "KW", label: "Kuwait" },
  { value: "LB", label: "Líbano" },
  { value: "LY", label: "Libia" },
  { value: "LT", label: "Lituania" },
  { value: "LU", label: "Luxemburgo" },
  { value: "MY", label: "Malasia" },
  { value: "MA", label: "Marruecos" },
  { value: "MX", label: "México" },
  { value: "NL", label: "Países Bajos" },
  { value: "NI", label: "Nicaragua" },
  { value: "NG", label: "Nigeria" },
  { value: "NO", label: "Noruega" },
  { value: "NZ", label: "Nueva Zelanda" },
  { value: "OM", label: "Omán" },
  { value: "PK", label: "Pakistán" },
  { value: "PA", label: "Panamá" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Perú" },
  { value: "PL", label: "Polonia" },
  { value: "PT", label: "Portugal" },
  { value: "PR", label: "Puerto Rico" },
  { value: "QA", label: "Catar" },
  { value: "GB", label: "Reino Unido" },
  { value: "CZ", label: "República Checa" },
  { value: "DO", label: "República Dominicana" },
  { value: "RO", label: "Rumanía" },
  { value: "RU", label: "Rusia" },
  { value: "SG", label: "Singapur" },
  { value: "ZA", label: "Sudáfrica" },
  { value: "SE", label: "Suecia" },
  { value: "CH", label: "Suiza" },
  { value: "TH", label: "Tailandia" },
  { value: "TW", label: "Taiwán" },
  { value: "TZ", label: "Tanzania" },
  { value: "TN", label: "Túnez" },
  { value: "TR", label: "Turquía" },
  { value: "UA", label: "Ucrania" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistán" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnam" },
] as const;
